Repository Android-Club-VITC/AC-Website-NextJs, pull requests merged in 2023-10, with the labels that each got.

#2 Set up repo
  app/layout.tsx
  app/page.tsx
  assets/logo.jpg
  components/Button.tsx
  components/Footer.tsx
  components/Header.tsx
  components/NavBar.tsx
Labels: hacktoberfest-accepted, hacktoberfest

#4 update readme
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#7 added Green Star Canvas
  app/layout.tsx
  components/canvas/Background_Stars.tsx
  package-lock.json
  package.json
  typings.d.ts
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#8 Added Odibee Font and Fixed Folder Structure.!
  app/(Home)/Section1.tsx
  app/layout.tsx
  app/page.tsx
  package-lock.json
  package.json
Labels: improvment, hacktoberfest-accepted, hacktoberfest, good first issue

#11 add favicon
  .gitignore
  app/favicon.ico
Labels: hacktoberfest-accepted, hacktoberfest

#13 added Dynamic Header with href links
  .gitignore
  .prettierignore
  .prettierrc.json
  README.md
  app/(Home)/Section1.tsx
  app/layout.tsx
  app/page.tsx
  components/Button.tsx
  components/Footer.tsx
  components/Header.tsx
  components/NavBar.tsx
  components/canvas/Background_Stars.tsx
  package-lock.json
  package.json
  typings.d.ts
Labels: hacktoberfest-accepted, hacktoberfest

#14 Issue#RequestPermissionToWorkOnOurWorkAndValueSection
  app/(Home)/Section2.tsx
  app/page.tsx
  assets/about/monitor1.svg
  assets/about/question.svg
  assets/about/scroll.svg
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#23 added consistentcy and made buttons working
  app/(Home)/Section1.tsx
  app/(Home)/Section2.tsx
  app/page.tsx
  components/Button.tsx
  components/Header.tsx
  package.json
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#25 added license and contributing.md
  CONTRIBUTING.md
  LICENSE
  README.md
  docs/ISSUES.md
  docs/PULL-REQUESTS.md
Labels: hacktoberfest-accepted, hacktoberfest

#30 fix run server command
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#31 section3 dev done - (have made the changes which was asked)
  app/(Home)/FooterCard.tsx
  app/(Home)/Section3.tsx
  app/(Home)/Section4.tsx
  app/page.tsx
  assets/team/aditya.png
  assets/team/atharv.png
  assets/team/ekta.png
  assets/team/geoffrey.png
  assets/team/karthik.png
  assets/team/kushagra.png
  assets/team/pranshu.jpeg
  assets/team/shrestha.png
  assets/team/shubham.png
  assets/team/sparsh.png
  assets/team/tushar.png
  components/Button.tsx
  components/Slider.tsx
  constants/events.tsx
  constants/ourTeam.tsx
  package.json
  typings.d.ts
Labels: hacktoberfest-accepted, hacktoberfest

#32 enhanced ui
  components/Slider.tsx
  tailwind.config.ts
Labels: hacktoberfest-accepted, hacktoberfest

#33 Folder structure fix new
  app/(Home)/Section1.tsx
  app/(Home)/Section2.tsx
  app/(Home)/Section3.tsx
  app/(Home)/Section4.tsx
  app/(Home)/Section7.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  assets/footer/card.svg
  components/Button.tsx
  components/Canvas/StarCanvas.tsx
  components/Events/EventCard.tsx
  components/Events/UpcomingEventCard.tsx
  components/Footer/Footer.tsx
  components/Footer/FooterCard.tsx
  components/Navbar/Navbar.tsx
  components/OurTeam/TeamSlider.tsx
  constants/navLinks.tsx
  constants/ourTeam.tsx
  constants/socialMedia.tsx
  package.json
Labels: hacktoberfest-accepted, hacktoberfest

#37 Value responsive
  app/(Home)/Section2.tsx
Labels: hacktoberfest-accepted, hacktoberfest

#38 Padding for mobile
  app/(Home)/Section1.tsx
Labels: hacktoberfest-accepted, hacktoberfest

#39 Title responsive
  app/(Home)/Section1.tsx
Labels: hacktoberfest-accepted, hacktoberfest

#40 Photo changed
  assets/team/sparsh.jpg
  assets/team/sparsh.png
  constants/ourTeam.tsx
Labels: hacktoberfest-accepted, hacktoberfest

#42 add responsive design
  app/(Home)/Section4.tsx
  components/Events/UpcomingEventCard.tsx
  components/Footer/FooterCard.tsx
  components/Navbar/Navbar.tsx
  components/OurTeam/TeamSlider.tsx
Labels: hacktoberfest-accepted, hacktoberfest
